# Generated by Django 5.0.8 on 2026-06-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_payment_discount_amount_payment_paid_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('influencer', 'Influenciador'), ('coach', 'Treinador'), ('academy', 'Academia'), ('ambassador', 'Embaixador'), ('other', 'Outro')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('payout_method', models.CharField(blank=True, choices=[('pix', 'Pix'), ('bank_transfer', 'Transferência bancária'), ('manual', 'Manual / a combinar')], max_length=20)),
                ('payout_details', models.CharField(blank=True, help_text='Chave Pix ou dados de repasse', max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='referrals_p_status_10564a_idx'), models.Index(fields=['type'], name='referrals_p_type_87161a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('plan_scope', models.CharField(choices=[('individual', 'Apenas Individual'), ('familia', 'Apenas Família'), ('both', 'Individual e Família')], default='both', max_length=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_total_uses', models.PositiveIntegerField(blank=True, help_text='NULL = ilimitado', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, default=1, help_text='Usos por cliente (0/NULL = ilimitado)', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Total de aplicações confirmadas (denormalizado)')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('expired', 'Expirado'), ('exhausted', 'Esgotado')], default='draft', max_length=12)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='referrals.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('percent', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rule_scope', models.CharField(choices=[('first_payment', 'Apenas 1º pagamento'), ('all_payments', 'Todos os pagamentos')], default='first_payment', max_length=15)),
                ('base_amount_type', models.CharField(choices=[('net_paid', 'Valor líquido pago'), ('gross_paid', 'Valor bruto pago')], default='net_paid', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=10)),
                ('coupon', models.ForeignKey(blank=True, help_text='Vazio = regra padrão do parceiro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='referrals.coupon')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='referrals.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('processing', 'Processando'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='draft', max_length=12)),
                ('method', models.CharField(blank=True, help_text='Método de repasse usado', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Comprovante/ID do repasse manual', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='referrals.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('paid', 'Paga'), ('reversed', 'Revertida'), ('canceled', 'Cancelada')], default='pending', max_length=10)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='billing.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='billing.subscription')),
                ('commission_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='referrals.commissionrule')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='referrals.coupon')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='referrals.partner')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='referrals.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='referrals_c_code_0c438c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='referrals_c_status_631043_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['status'], name='referrals_c_status_4c08bc_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='referrals_p_status_e226df_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['partner', '-created_at'], name='referrals_p_partner_cc32e9_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['status'], name='referrals_c_status_218d49_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['partner', 'status'], name='referrals_c_partner_958902_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionledger',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='uniq_commission_per_payment'),
        ),
    ]
