# Generated by Django 5.0.6 on 2026-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='connector_key',
            field=models.CharField(help_text='Key matching a connector class (e.g. fpt_sp_public, cbt_public)', max_length=100),
        ),
    ]
