# Generated by Django 5.0.6 on 2026-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_pushsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertpreference',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useralertpreference',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
