# Generated by Django 5.0.6 on 2026-05-06 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerprofile_home_coords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playercategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playerprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playerprofilecategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='playercategory',
            constraint=models.UniqueConstraint(fields=('taxonomy', 'code', 'gender_scope'), name='unique_taxonomy_code_gender'),
        ),
        migrations.AddConstraint(
            model_name='playerprofile',
            constraint=models.UniqueConstraint(fields=('user', 'display_name'), name='unique_user_display_name'),
        ),
        migrations.AddConstraint(
            model_name='playerprofilecategory',
            constraint=models.UniqueConstraint(fields=('profile', 'category'), name='unique_profile_category'),
        ),
    ]
