# Generated by Django 5.0.6 on 2026-05-08 23:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_playercategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='travel_states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='UFs where the player accepts travelling to compete (e.g. ["SP","RJ","MG"]). Empty = not set.', size=None),
        ),
    ]
