# Generated by Django 5.0.6 on 2026-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_playerprofile_utr_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ti_player_id', models.CharField(db_index=True, help_text='Numeric Tênis Integrado profile id (perfil2/index/{id})', max_length=20)),
                ('player_name', models.CharField(max_length=200)),
                ('player_name_normalized', models.CharField(blank=True, db_index=True, help_text='Accent/case-folded name used for auto-linking lookups', max_length=200)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('cbt', 'CBT — Confederação Brasileira de Tênis'), ('fpt', 'FPT — Federação Paulista de Tênis'), ('fct', 'FCT — Federação Catarinense de Tênis'), ('fbt', 'FBT — Federação Baiana de Tênis')], db_index=True, max_length=20)),
                ('federation', models.CharField(blank=True, max_length=120)),
                ('ranking_external_id', models.CharField(db_index=True, help_text='TI ranking id (ranking_painel_classif/index/{id})', max_length=20)),
                ('ranking_name', models.CharField(blank=True, max_length=200)),
                ('category_code', models.CharField(blank=True, help_text='TI id_categoria value', max_length=20)),
                ('category_label', models.CharField(blank=True, max_length=200)),
                ('modality', models.CharField(blank=True, default='', max_length=40)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.CharField(blank=True, max_length=20)),
                ('wtn', models.CharField(blank=True, max_length=20)),
                ('season', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('classified_at', models.DateField(blank=True, help_text='Cut-off (corte) date of the standing', null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('confidence', models.CharField(choices=[('high', 'Alta — página oficial pública'), ('medium', 'Média'), ('low', 'Baixa')], default='high', max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'ranking_external_id', 'category_code', 'position'],
                'indexes': [models.Index(fields=['player_name_normalized'], name='players_ext_player__9cb212_idx'), models.Index(fields=['ti_player_id'], name='players_ext_ti_play_89006a_idx'), models.Index(fields=['source', 'ranking_external_id'], name='players_ext_source_777785_idx'), models.Index(fields=['source', 'season'], name='players_ext_source_692e9e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='externalplayerranking',
            constraint=models.UniqueConstraint(fields=('source', 'ranking_external_id', 'category_code', 'ti_player_id', 'season'), name='unique_external_ranking_entry'),
        ),
    ]
