# Generated by Django 5.0.6 on 2026-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_externalplayerranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalplayerranking',
            name='source',
            field=models.CharField(choices=[('cbt', 'CBT — Confederação Brasileira de Tênis'), ('fpt', 'FPT — Federação Paulista de Tênis'), ('fct', 'FCT — Federação Catarinense de Tênis'), ('fbt', 'FBT — Federação Baiana de Tênis'), ('fed', 'Federação (via Tênis Integrado)')], db_index=True, max_length=20),
        ),
    ]
