# Generated by Django 5.0.6 on 2026-06-05 14:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_externalplayerranking_source'),
        ('sources', '0002_alter_datasource_connector_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='federation',
            field=models.ForeignKey(blank=True, help_text='Single federation the player competes for. Its UF (state) drives eligibility/location filtering. Replaces the legacy travel_states.', limit_choices_to={'type': 'federation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to='sources.organization'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='travel_states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='Legacy/fallback: UFs where the player accepts travelling to compete (e.g. ["SP","RJ","MG"]). Superseded by `federation`. Empty = not set.', size=None),
        ),
    ]
