# Generated by Django 5.0.6 on 2026-06-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_seed_federations_and_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='tennis_class',
        ),
    ]
