# Generated by Django 5.0.6 on 2026-06-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_remove_playerprofile_tennis_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='competitive_level',
            field=models.CharField(choices=[('kids', 'Crianças'), ('youth', 'Juvenil'), ('pro', 'Profissional'), ('seniors', 'Idosos')], default='pro', max_length=20),
        ),
    ]
