# Generated by Django 5.0.6 on 2026-05-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_federationentry_source_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentry',
            name='player_country_code',
            field=models.CharField(blank=True, default='', help_text='Código ISO do país (ex: ARG, BR) conforme publicado pela fonte', max_length=10),
        ),
        migrations.AddField(
            model_name='federationentry',
            name='player_country_name',
            field=models.CharField(blank=True, default='', help_text='País/nacionalidade do atleta conforme publicado pela fonte (ex: Argentina)', max_length=100),
        ),
    ]
