# Generated by Django 5.0.6 on 2026-06-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_pg_trgm_gin_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchinglog',
            new_name='registratio_entry_i_bb7aaf_idx',
            old_name='matchinglog_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='matchinglog',
            new_name='registratio_profile_384ee3_idx',
            old_name='matchinglog_profile_idx',
        ),
    ]
