# Generated by Django 5.0.8 on 2026-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_rename_matchinglog_entry_idx_registratio_entry_i_bb7aaf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentry',
            name='player_age',
            field=models.PositiveIntegerField(blank=True, help_text='Idade do atleta conforme a fonte, quando disponível.', null=True),
        ),
        migrations.AddField(
            model_name='federationentry',
            name='player_ti_id',
            field=models.CharField(blank=True, default='', help_text='ID do jogador no Tênis Integrado (id_tenista), quando disponível.', max_length=20),
        ),
        migrations.AddField(
            model_name='federationentry',
            name='player_uf',
            field=models.CharField(blank=True, default='', help_text='UF do atleta (ex: SP), quando disponível.', max_length=2),
        ),
    ]
