# Generated by Django 5.0.6 on 2026-06-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_federationentry_player_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentry',
            name='draw_section',
            field=models.CharField(blank=True, default='', help_text='Seção do quadro conforme a fonte (ex.: Main, Qualifying, Alternates).', max_length=40),
        ),
    ]
