# Generated by Django 5.0.6 on 2026-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_federationentry_draw_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinglog',
            name='match_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='matchinglog',
            name='method',
            field=models.CharField(choices=[('external_id', 'ID externo (match exato)'), ('name_fuzzy', 'Nome fuzzy (SequenceMatcher)'), ('name_token', 'Nome por tokens (COSAT/ITF/UTR)'), ('none', 'Sem correspondência')], default='none', max_length=20),
        ),
    ]
