# Generated by Django 5.0.8 on 2026-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_matchinglog_match_reason_alter_matchinglog_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentry',
            name='source_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Ordem em que o inscrito aparece na fonte (site). Usada para exibir a lista na MESMA ordem do site, em vez de ordenar por nome/ranking. Menor = aparece antes.', null=True),
        ),
    ]
