# Generated by Django 5.0.6 on 2026-05-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_max_members_familymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
