# Generated by Django 5.0.8 on 2026-06-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment_discount_amount_payment_paid_net_amount'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='referrals.coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='referrals.partner'),
        ),
    ]
