# Generated by Django 5.0.8 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_subscription_asaas_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_members',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Total de perfis permitidos (responsáveis + dependentes). Individual=1, Família=5.',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_responsibles',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text=(
                    'Quantos perfis de responsável (titular + co-responsáveis) podem '
                    'compartilhar esta assinatura. Dependentes permitidos = '
                    'max_members - max_responsibles.'
                ),
            ),
        ),
    ]
