# Generated by Django 5.0.6 on 2026-05-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parentchild'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachathlete',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parentchild',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coachathlete',
            constraint=models.UniqueConstraint(fields=('coach', 'athlete'), name='unique_coach_athlete'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_parent_child'),
        ),
    ]
