# Generated by Django 5.0.6 on 2026-06-07 19:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_dependentinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dependentinvite',
            new_name='accounts_de_invitee_54700d_idx',
            old_name='accounts_de_invitee_idx',
        ),
        migrations.RenameIndex(
            model_name='dependentinvite',
            new_name='accounts_de_parent__298afa_idx',
            old_name='accounts_de_parent_idx',
        ),
        migrations.AlterField(
            model_name='dependentinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dependentinvite',
            name='expires_at',
            field=models.DateTimeField(default=apps.accounts.models._invite_expires),
        ),
        migrations.AlterField(
            model_name='dependentinvite',
            name='token',
            field=models.CharField(default=apps.accounts.models._invite_token, editable=False, max_length=64, unique=True),
        ),
    ]
