# Generated by Django 5.0.8 on 2026-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_login_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF, somente dígitos', max_length=11),
        ),
    ]
