# Generated by Django 5.0.8 on 2026-06-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_cpf'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='unique_cpf_when_present'),
        ),
    ]
