# Generated by Django 5.0.8 on 2026-06-17 02:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_unique_cpf_when_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.accounts.models._reg_token, editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='player', max_length=20)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('plan_slug', models.CharField(default='tester', max_length=30)),
                ('billing_period', models.CharField(default='monthly', max_length=10)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('email_verified', models.BooleanField(default=False)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=60)),
                ('consumed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models._reg_expires)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_pe_email_d113e3_idx'), models.Index(fields=['consumed', 'expires_at'], name='accounts_pe_consume_ee770f_idx')],
            },
        ),
    ]
