# Generated by Django 5.0.8 on 2026-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='asaas_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
