# Generated by Django 5.0.6 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_pendingregistration_asaas_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Jogador'), ('coach', 'Treinador'), ('parent', 'Pai/Responsável'), ('admin', 'Administrador'), ('partner', 'Parceiro')], default='player', max_length=20),
        ),
    ]
