# Generated by Django 5.0.6 on 2026-05-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentedition_tournaments_dedup_f_ece981_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentedition',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='False = oculto da listagem pública (admin pode editar e republicar).'),
        ),
    ]
