# Generated by Django 5.0.6 on 2026-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_unique_edition_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentedition',
            name='acceptance_list',
            field=models.JSONField(blank=True, default=list, help_text='Lista de inscritos por seção: [{"section": "main_draw", "players": [{"name", "country", "country_code", "ranking", "wtn", "priority", "information"}]}]'),
        ),
    ]
