# Generated by Django 5.2.15 on 2026-07-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_tournamentedition_acceptance_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentedition',
            name='is_kids',
            field=models.BooleanField(db_index=True, default=False, help_text='True = torneio tem categoria(s) Kids (abaixo de 12 anos).'),
        ),
    ]
