from django.urls import path
from .views import (
    dashboard, review_queue, stats,
    user_list, user_detail, user_set_password,
    user_unlock_login, user_set_plan, user_manage_link,
    edition_patch, edition_create, admin_editions_list,
    data_sources_list, data_source_patch, connector_status,
    ingestion_runs_list, execution_logs,
    trigger_itf_sync, trigger_cosat_sync, debug_itf_sample, trigger_db_cleanup,
    waitlist_leads,
)
from .referrals_views import (
    partners, partner_detail, coupons, coupon_detail,
    commission_rules, commission_rule_detail,
    commissions, commission_detail, commissions_summary,
    payouts, payout_detail,
)

urlpatterns = [
    path('dashboard/', dashboard, name='admin-dashboard'),
    path('review-queue/', review_queue, name='admin-review-queue'),
    path('stats/', stats, name='admin-stats'),
    path('users/', user_list, name='admin-user-list'),
    path('users/<int:pk>/', user_detail, name='admin-user-detail'),
    path('users/<int:pk>/set-password/', user_set_password, name='admin-user-set-password'),
    path('users/<int:pk>/unlock-login/', user_unlock_login, name='admin-user-unlock-login'),
    path('users/<int:pk>/plan/', user_set_plan, name='admin-user-set-plan'),
    path('users/<int:pk>/links/', user_manage_link, name='admin-user-manage-link'),
    path('editions/', edition_create, name='admin-edition-create'),
    path('editions-list/', admin_editions_list, name='admin-editions-list'),
    path('editions/<int:pk>/', edition_patch, name='admin-edition-patch'),
    path('sources/', data_sources_list, name='admin-sources-list'),
    path('sources/<int:pk>/', data_source_patch, name='admin-source-patch'),
    path('connector-status/', connector_status, name='admin-connector-status'),
    path('runs/', ingestion_runs_list, name='admin-runs-list'),
    path('execution-logs/', execution_logs, name='admin-execution-logs'),
    path('sync/itf/', trigger_itf_sync, name='admin-sync-itf'),
    path('sync/cosat/', trigger_cosat_sync, name='admin-sync-cosat'),
    path('debug/itf-sample/', debug_itf_sample, name='admin-debug-itf-sample'),
    path('maintenance/cleanup/', trigger_db_cleanup, name='admin-db-cleanup'),
    path('waitlist-leads/', waitlist_leads, name='admin-waitlist-leads'),

    # Programa de parceiros (cupons/comissões/repasses) — master apenas
    path('partners/', partners, name='admin-partners'),
    path('partners/<int:pk>/', partner_detail, name='admin-partner-detail'),
    path('coupons/', coupons, name='admin-coupons'),
    path('coupons/<int:pk>/', coupon_detail, name='admin-coupon-detail'),
    path('commission-rules/', commission_rules, name='admin-commission-rules'),
    path('commission-rules/<int:pk>/', commission_rule_detail, name='admin-commission-rule-detail'),
    path('commissions/', commissions, name='admin-commissions'),
    path('commissions/summary/', commissions_summary, name='admin-commissions-summary'),
    path('commissions/<int:pk>/', commission_detail, name='admin-commission-detail'),
    path('payouts/', payouts, name='admin-payouts'),
    path('payouts/<int:pk>/', payout_detail, name='admin-payout-detail'),
]
